/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 bellpepper_step6.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/glb/bellpepper_step6-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -3, 0]}
        rotation={[Math.PI, -0.81, Math.PI]}
        scale={10}
      >
        <mesh geometry={nodes["result-5"].geometry} material={materials.stem} />
        <mesh
          geometry={nodes["result-5_1"].geometry}
          material={materials.petals}
        />
        <mesh
          geometry={nodes["result-5_2"].geometry}
          material={materials.stamens}
        />
        <mesh
          geometry={nodes["result-5_3"].geometry}
          material={materials.leaf_disease}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/bellpepper_step6-transformed.glb");
