/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 chart.gltf --transform
Author: LasquetiSpice (https://sketchfab.com/LasquetiSpice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pulldown-graph-chart-3d-98e6c7b216d84a5380d11c7a601a9bcb
Title: Pulldown Graph Chart 3D
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/glb/chart-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Primitive_Material}
        position={[0, 1.76, 0.13]}
        scale={[3.01, 2.46, 0.1]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Primitive_Material_0}
        position={[0, 2.94, 0.13]}
        scale={[3.12, 0.38, 0.17]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Primitive_Material_1}
        position={[0, 0.51, 0.12]}
        scale={[0.09, 0.56, 0.09]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.Primitive_Material_1}
        position={[0, 0.12, 0.12]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.Primitive_Material_3}
        position={[0.86, 2.17, 0.07]}
        scale={[0.79, 0.79, 0.06]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.Primitive_Material_4}
        position={[-0.21, 2.43, 0.06]}
        scale={[1.07, 0.12, 0.05]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.Primitive_Material_copy}
        position={[-0.21, 1.91, 0.06]}
        scale={[1.07, 0.12, 0.05]}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.Primitive_Material_copy}
        position={[-0.21, 2.18, 0.06]}
        scale={[1.07, 0.12, 0.05]}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.Primitive_Material_copy}
        position={[0.85, 1.61, 0.06]}
        scale={[0.67, 0.12, 0.05]}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.Primitive_Material_5}
        position={[-0.38, 0.83, -0.08]}
        scale={[1.77, 0.1, 0.41]}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials.Primitive_Material_3}
        position={[0.23, 1.1, -0.1]}
        scale={[0.27, 0.45, 0.27]}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.Primitive_Material_3}
        position={[-0.98, 1.38, -0.1]}
        scale={[0.27, 1.04, 0.27]}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.Primitive_Material_3}
        position={[-0.58, 1.24, -0.1]}
        scale={[0.27, 0.74, 0.27]}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.Primitive_Material_3}
        position={[-0.17, 1.16, -0.1]}
        scale={[0.27, 0.6, 0.27]}
      />
    </group>
  );
}

useGLTF.preload("/glb/chart-transformed.glb");
